### ISSUE TITLE
Content: Hotjar feedback, polls, etc.

### ISSUE THREAD

**Issue by kareninsignares** [emfoundation/smf-prototype#171]
Dale to create the shape/create the Hotjar feedback tools: Incoming (feedback), polls, and (surveys).

**Comment by kareninsignares** [comment]
@dalwal08 In Hotjar we need to make the feedback under https://**prototype**.circulareconomy.space/ **NOT** https://**smf**prototype.circulareconomy.space/ as George changed the server :)

https://insights.hotjar.com/sites/939875/feedback/responses/83023

**Comment by dalwal08** [comment]
@kareninsignares and @vicky-d1 I'm not sure I'm the best person to do the incoming feedback as that feels more related/useful to usability testing than to the content. I have set up a poll for the completion page on each learning path that seeks to understand if users completed the whole path and if they learnt anything.

That said if you don't need to use the incoming feedback tab for usability testing because you feel you are capturing that in other ways then I'm happy to set it to simply ask "How would you rate the content on this page?"
