### ISSUE TITLE
Add Next/Previous chapter button to bottom of Chapter Page (above tags, button at the bottom saying "Next Chapter")

### ISSUE THREAD

**Issue by kareninsignares** [emfoundation/smf-prototype#97]

**Comment by kareninsignares** [comment]
Assigning to everyone FYI.

**Comment by MicrosoftDan** [comment]
Hi All,

Mock up for concept of previous/next buttons. Greyed out when on chapter 1 obviously and then arrow highlights blue on hover.

Mobile version -  I did try and keep the word ‘chapter’ but the text was getting just too small to read.

Cheers,

Dan

**Comment by MicrosoftDan** [comment]
![chapter arrows mobile](https://user-images.githubusercontent.com/36270652/41284547-85afccc4-6e31-11e8-88d6-9589f706117a.jpg)
![chapter arrows](https://user-images.githubusercontent.com/36270652/41284548-85d26c48-6e31-11e8-81f6-fec1a501b955.jpg)

**Comment by kareninsignares** [comment]
Thanks, @MicrosoftDan.  Looks good!

**Comment by asimonw** [comment]
@MicrosoftDan @kareninsignares Could it also work for you guys with the buttons underneath the tags? Technically it would be more straight forward because the tags are still part of the individual chapter content while the functionality is already build for the top nav, which part of the "frame".

From a content hierarchy it could also make sense (possibly less confusing?) to have the navigation be "outside" of all content related to the chapter.

If it's important, I should be able to work around it.

**Comment by MicrosoftDan** [comment]
I'm fine with that but will let the SMF team have the final say

**Comment by kareninsignares** [comment]
I'm also fine with that, Alex. I think the 'to-do' list is long for this prototype and I want to avoid you guys spend your time in the little details... I will say that we can leave it with the buttons underneath for now.  @dalwal08  Is it really important to have them above the tags?
